export const GET_USER_LOGIN_REQUEST = "GET_USER_LOGIN_REQUEST";
export const GET_USER_LOGIN_SUCCESS = "GET_USER_LOGIN_SUCCESS";
export const GET_USER_LOGIN_FAILURE = "GET_USER_LOGIN_FAILURE";

export const GET_USER_LOGOUT_REQUEST = "GET_USER_LOGOUT_REQUEST";
export const GET_USER_LOGOUT_SUCCESS = "GET_USER_LOGOUT_SUCCESS";
export const GET_USER_LOGOUT_FAILURE = "GET_USER_LOGOUT_FAILURE";
